name: record_windows
description: Record Windows implementation.
version: 0.0.1
homepage: https://github.com/llfbandit/record/tree/master/record_windows

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: RecordWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
